/* tslint:disable */
/* eslint-disable */
/**
 * Afkae. Brothers - AsSeen API
 * API documentation for Afkae. Brothers - AsSeen
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppInfoGet200ResponseAllOfData
 */
export interface AppInfoGet200ResponseAllOfData {
    /**
     * 
     * @type {string}
     * @memberof AppInfoGet200ResponseAllOfData
     */
    appVersion: string;
    /**
     * 
     * @type {string}
     * @memberof AppInfoGet200ResponseAllOfData
     */
    appBundleURL: string;
}

/**
 * Check if a given object implements the AppInfoGet200ResponseAllOfData interface.
 */
export function instanceOfAppInfoGet200ResponseAllOfData(value: object): value is AppInfoGet200ResponseAllOfData {
    if (!('appVersion' in value) || value['appVersion'] === undefined) return false;
    if (!('appBundleURL' in value) || value['appBundleURL'] === undefined) return false;
    return true;
}

export function AppInfoGet200ResponseAllOfDataFromJSON(json: any): AppInfoGet200ResponseAllOfData {
    return AppInfoGet200ResponseAllOfDataFromJSONTyped(json, false);
}

export function AppInfoGet200ResponseAllOfDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppInfoGet200ResponseAllOfData {
    if (json == null) {
        return json;
    }
    return {
        
        'appVersion': json['appVersion'],
        'appBundleURL': json['appBundleURL'],
    };
}

export function AppInfoGet200ResponseAllOfDataToJSON(json: any): AppInfoGet200ResponseAllOfData {
    return AppInfoGet200ResponseAllOfDataToJSONTyped(json, false);
}

export function AppInfoGet200ResponseAllOfDataToJSONTyped(value?: AppInfoGet200ResponseAllOfData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'appVersion': value['appVersion'],
        'appBundleURL': value['appBundleURL'],
    };
}

