/* tslint:disable */
/* eslint-disable */
/**
 * Afkae. Brothers - AsSeen API
 * API documentation for Afkae. Brothers - AsSeen
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppInfoGet200ResponseAllOfData } from './AppInfoGet200ResponseAllOfData';
import {
    AppInfoGet200ResponseAllOfDataFromJSON,
    AppInfoGet200ResponseAllOfDataFromJSONTyped,
    AppInfoGet200ResponseAllOfDataToJSON,
    AppInfoGet200ResponseAllOfDataToJSONTyped,
} from './AppInfoGet200ResponseAllOfData';

/**
 * 
 * @export
 * @interface AppInfoGet200Response
 */
export interface AppInfoGet200Response {
    /**
     * 
     * @type {string}
     * @memberof AppInfoGet200Response
     */
    message: string;
    /**
     * 
     * @type {AppInfoGet200ResponseAllOfData}
     * @memberof AppInfoGet200Response
     */
    data: AppInfoGet200ResponseAllOfData;
}

/**
 * Check if a given object implements the AppInfoGet200Response interface.
 */
export function instanceOfAppInfoGet200Response(value: object): value is AppInfoGet200Response {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AppInfoGet200ResponseFromJSON(json: any): AppInfoGet200Response {
    return AppInfoGet200ResponseFromJSONTyped(json, false);
}

export function AppInfoGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppInfoGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'data': AppInfoGet200ResponseAllOfDataFromJSON(json['data']),
    };
}

export function AppInfoGet200ResponseToJSON(json: any): AppInfoGet200Response {
    return AppInfoGet200ResponseToJSONTyped(json, false);
}

export function AppInfoGet200ResponseToJSONTyped(value?: AppInfoGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'data': AppInfoGet200ResponseAllOfDataToJSON(value['data']),
    };
}

