/* tslint:disable */
/* eslint-disable */
/**
 * Afkae. Brothers - AsSeen API
 * API documentation for Afkae. Brothers - AsSeen
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthMeGet200Response
 */
export interface AuthMeGet200Response {
    /**
     * 
     * @type {string}
     * @memberof AuthMeGet200Response
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AuthMeGet200Response
     */
    email: string;
    /**
     * 
     * @type {boolean}
     * @memberof AuthMeGet200Response
     */
    emailVerified?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AuthMeGet200Response
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AuthMeGet200Response
     */
    image?: string;
    /**
     * 
     * @type {Date}
     * @memberof AuthMeGet200Response
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AuthMeGet200Response
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the AuthMeGet200Response interface.
 */
export function instanceOfAuthMeGet200Response(value: object): value is AuthMeGet200Response {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function AuthMeGet200ResponseFromJSON(json: any): AuthMeGet200Response {
    return AuthMeGet200ResponseFromJSONTyped(json, false);
}

export function AuthMeGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthMeGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'emailVerified': json['emailVerified'] == null ? undefined : json['emailVerified'],
        'name': json['name'],
        'image': json['image'] == null ? undefined : json['image'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function AuthMeGet200ResponseToJSON(json: any): AuthMeGet200Response {
    return AuthMeGet200ResponseToJSONTyped(json, false);
}

export function AuthMeGet200ResponseToJSONTyped(value?: AuthMeGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'emailVerified': value['emailVerified'],
        'name': value['name'],
        'image': value['image'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

