/* tslint:disable */
/* eslint-disable */
/**
 * Afkae. Brothers - AsSeen API
 * API documentation for Afkae. Brothers - AsSeen
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SetupUserGet201ResponseData } from './SetupUserGet201ResponseData';
import {
    SetupUserGet201ResponseDataFromJSON,
    SetupUserGet201ResponseDataFromJSONTyped,
    SetupUserGet201ResponseDataToJSON,
    SetupUserGet201ResponseDataToJSONTyped,
} from './SetupUserGet201ResponseData';

/**
 * 
 * @export
 * @interface SetupUserGet201Response
 */
export interface SetupUserGet201Response {
    /**
     * 
     * @type {string}
     * @memberof SetupUserGet201Response
     */
    message: string;
    /**
     * 
     * @type {SetupUserGet201ResponseData}
     * @memberof SetupUserGet201Response
     */
    data: SetupUserGet201ResponseData;
}

/**
 * Check if a given object implements the SetupUserGet201Response interface.
 */
export function instanceOfSetupUserGet201Response(value: object): value is SetupUserGet201Response {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SetupUserGet201ResponseFromJSON(json: any): SetupUserGet201Response {
    return SetupUserGet201ResponseFromJSONTyped(json, false);
}

export function SetupUserGet201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetupUserGet201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'data': SetupUserGet201ResponseDataFromJSON(json['data']),
    };
}

export function SetupUserGet201ResponseToJSON(json: any): SetupUserGet201Response {
    return SetupUserGet201ResponseToJSONTyped(json, false);
}

export function SetupUserGet201ResponseToJSONTyped(value?: SetupUserGet201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'data': SetupUserGet201ResponseDataToJSON(value['data']),
    };
}

