/* tslint:disable */
/* eslint-disable */
/**
 * Afkae. Brothers - AsSeen API
 * API documentation for Afkae. Brothers - AsSeen
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetupUserGet201ResponseData
 */
export interface SetupUserGet201ResponseData {
    /**
     * 
     * @type {string}
     * @memberof SetupUserGet201ResponseData
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof SetupUserGet201ResponseData
     */
    dbName: string;
}

/**
 * Check if a given object implements the SetupUserGet201ResponseData interface.
 */
export function instanceOfSetupUserGet201ResponseData(value: object): value is SetupUserGet201ResponseData {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('dbName' in value) || value['dbName'] === undefined) return false;
    return true;
}

export function SetupUserGet201ResponseDataFromJSON(json: any): SetupUserGet201ResponseData {
    return SetupUserGet201ResponseDataFromJSONTyped(json, false);
}

export function SetupUserGet201ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetupUserGet201ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'dbName': json['dbName'],
    };
}

export function SetupUserGet201ResponseDataToJSON(json: any): SetupUserGet201ResponseData {
    return SetupUserGet201ResponseDataToJSONTyped(json, false);
}

export function SetupUserGet201ResponseDataToJSONTyped(value?: SetupUserGet201ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'dbName': value['dbName'],
    };
}

